# Generated by Django 5.0.1 on 2024-02-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='redate',
            field=models.CharField(max_length=20),
        ),
    ]
